### ISSUE TITLE
TypeError: Workfront.NodeApi is not a constructor

### ISSUE THREAD

**Issue by bigdatacreative** [Workfront/workfront-api#1035]
Hi There,

I'm facing the issue: TypeError: Workfront.NodeApi is not a constructor
My code:
const Workfront = require('workfront-api');
var instance = new Workfront.NodeApi({
    url: 'xxx',
    version: '5.0'
});

if I log Workfront I get:
{
   default: {
     NodeApi: [Function: NodeApi],
     ResponseHandler: [Getter],
     Api: [Function: NodeApi]
   }
 }

Note: Node version: 14.x

What am I doing wrong?
Thank you!

n

**Comment by bigdatacreative** [comment]
Still not working guys

**Comment by citizensas** [comment]
> Still not working guys

We have some trouble publishing the new version. We'll come back soon.
Sorry about that.

**Comment by bigdatacreative** [comment]
Thx!!

**Comment by citizensas** [comment]
A new version of `workfront-api` has been published. 

@bigdatacreative Please install the version `8.1.0` and let me know if the issue is resolved.

**Comment by bigdatacreative** [comment]
All good! Thank you!
