### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [Workfront/workfront-api#17]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of workfront-api (v 1.3.4) our tools detected approximately 249 unused function in dependencies. Removing those functions, the size of workfront-api bundled could be reduced at least 7% (All tests passed). I’m attaching the reduced version of your project. 
[workfront(optimized).txt](https://github.com/Workfront/workfront-api/files/671182/workfront.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by bhovhannes** [comment]
Just to make sure I am understanding the term UFF correctly, can you please list some of these 249 functions?
Did you found them in dependencies or in workfront-api code?

Right now we're working of move from browserify to webpack. We only have very preliminary results, but we saw that with webpack bundle is significantly smaller.

**Comment by bhovhannes** [comment]
So, currently we use webpack for bundling and bundle size is now 5.24KB minified.
Closing this issue.
