### ISSUE TITLE
Workfront API : PUT request returned data but nothing updated in Project object

### ISSUE THREAD

**Issue by sanskritiagarwal** [Workfront/workfront-api#222]
My Request URL : 

https://mycompany.my.workfront.com/attask/api/v7.0/proj/5a271b00005b0be97863c26861fdb82c?sessionID=aeeaf5fd93b642e28a66528f08c2f978&updates={"name":"TEST API ","status":"CUR","hours":[{"hours":30,"status":"BA"},{"hours":57,"status":"SUB"}]}&fields=ID,status,name,hours

It returned data but doesnt update anything.

**Comment by citizensas** [comment]
Can you provide the version of `workfront-api` you used for your request?

**Comment by sanskritiagarwal** [comment]
7.0

**Comment by citizensas** [comment]
I was asking the version of `workfront-api` not the version of Workfront Public API. `workfront-api` latest version is 4.4.0.

**Comment by sanskritiagarwal** [comment]
From where would I know that...

I found @version 2009-04-14 in one of the files...

**Comment by sanskritiagarwal** [comment]
I am using StremClient java app

**Comment by citizensas** [comment]
`workfront-api` is an API for Node.js and/or Javascript for Web. 
Please contact with the customer support if you need help with your issue.
