### ISSUE TITLE
Trouble converting outstanding request (issue) into project via API

### ISSUE THREAD

**Issue by dtparks** [Workfront/workfront-api#471]
Hi there,

I am trying to convert an issue (request) to a project via API v10.0. 

My request is as follows
```
https://testdrive.my.workfront.com/attask/api/v10.0/issue/5c7ee9660008672d9f4d86116dffd157/convertToProject/?apiKey=[removed]
```
I am getting a 500 internal server error with the following message
```
{
    "error": {
        "class": "java.lang.NullPointerException",
        "message": null,
        "title": null,
        "msgKey": "exception.attask",
        "attributes": [
            ""
        ],
        "code": 0
    }
}
```
I know I'm probably missing a few parameters but I am unable to find examples via the docs on Workfront's website. Do I need a template parameter as well? If so what is the format? Any help would be much appreciated.

**Comment by citizensas** [comment]
@dtparks your request is almost correct. All you need to do is to add the name of the project you want to create. 
```
https://testdrive.my.workfront.com/attask/api/v10.0/issue/5c7ee9660008672d9f4d86116dffd157/convertToProject?updates={"project":{"name":"your project name"}}&apiKey=[removed]
```

This repo is actually a javascript tool for Workfront API. You're welcome to use it if you code in NodeJS. If that's the case, your request will look something like this.
```js
api.execute("issue", "5c7ee9660008672d9f4d86116dffd157", "convertToProject", {
   name: "your project name"
});
```

**Comment by dtparks** [comment]
That worked! Thank you.

**Comment by dtparks** [comment]
One last question, how would I go about attaching a template to the project after converting it from an issue?

**Comment by citizensas** [comment]
Assuming you already have a Template, then the request is pretty similar to the one above.
```
https://testdrive.my.workfront.com/attask/api/v10.0/project/PROJECT_ID/attachTemplate?updates={"templateID":"TEMPLATE_ID"}&apiKey=[removed]
```
Replace `PROJECT_ID` with the project ID you just converted from the issue, and the `TEMPLATE_ID` is the existing template ID you want to attach.

**Comment by dtparks** [comment]
Thank you very much 👍

**Comment by dtparks** [comment]
Apologies for reopening the issue and thanks for your continued help.

I am now dealing with an issue where if I submit an issue and then convert it to a project with a template, the custom form that was initially submitted for the request is not preserved when it is converted into a project. Specifically, it does not appear in the project details portion of the newly converted project. It shows up fine if converted manually without any API requests. 

Is there a way you know of to keep the custom form when converting to a project?

**Comment by dtparks** [comment]
Apologies for reopening the issue and thanks for your continued help.

I am now dealing with an issue where if I submit an issue with custom form data inputted and then convert it to a project with a template, the custom form that was initially submitted for the request is not preserved when it is converted into a project. Specifically, it does not appear in the project details portion of the newly converted project or in the requests tab when it displays "originally submitted as___"  It shows up fine if converted manually without any API requests.

Is there a way you know of to keep the custom form when converting to a project?

Using this API request
`https://qualcomm-osr122018demo.my.workfront.com/attask/api/v10.0/issue/5c81ae4600024cc971331eb8b29fdf7d/convertToProject?apiKey=923v3xy0wjud3ir1wg8m7q0eg6yqm59n&updates={
    "project": {
        "name": "Email nvidia about website ad",
        "templateID" : "5c194ec9000f9c8e7cec22dd8538c30d"     
        }
}`

**Comment by citizensas** [comment]
@dtparks your issue can be addressed to technical support, they might help you better.
From my part, I can tell you how to make `preserveIssue` work.
```
https://<Hostname>/attask/api/v10.0/issue/[ID]/convertToProject?apiKey=[REMOVED]&updates={ "project": { "name": "Project name test", "templateID" : "[TemplateID]" }, "options": ["preserveIssue"] }
```
I hope this helps you.

**Comment by dtparks** [comment]
Thank you @citizensas
