### ISSUE TITLE
Feature: add method type support for nodebalancer

### ISSUE THREAD

**Issue by bhovhannes** [Workfront/workfront-api#5]
The nodebalancer does not support PUT and DELETE, so in order to use a those methods they have to be in the query string (Ex. URL?menthod=put).

**Comment by bhovhannes** [comment]
Message from Ryan Miller:

> I have come up with two possible solutions and would like some feedback. 
> 1. Add a flag to all put and delete calls that says to use query params. 
> 2. make the use of query params the default.

**Comment by bhovhannes** [comment]
@Ryan Miller, I think 3rd solution is the best one. 
We already have done some work related with jsonp support and 3rd solution is in sync with our changes.
Also, that way we will not change signatures of existing methods much or add new methods, that is, 3rd solution will introduce minimal changes in code.
Please set config option name to `alwaysUseGet`, and it should be boolean and default to `false`.

**Comment by RPMiller** [comment]
I have a local branch that adds support for this, but I cannot push it up since I do not have access. Should I fork the repo, push it to the fork and then do a pull request from there?
