### ISSUE TITLE
Example Browser Login.html page http://localhost:8000/dist/workfront.js 404 Not Found

### ISSUE THREAD

**Issue by Micchavez** [Workfront/workfront-api#576]
Steps to reproduce:

`git clone git://github.com/Workfront/workfront-api.git`
`cd workfront-api`
`npm install`
`npm start`
go to [http://localhost:8000/examples/browser/login.html](http://localhost:8000/examples/browser/login.html)

Then look in the console, it says: `Failed to load resource: the server responded with a status of 404 (Not Found)`

Dont see workfront.js in the dist directory:
```
workfront-api.cjs.js
workfront-api.cjs.js.map
workfront-api.es.js
workfront-api.es.js.map
workfront-api.umd.js
workfront-api.umd.js.map
workfront-api.umd.min.js
workfront-api.umd.min.js.map
```

Changing the script tag to: `dist/workfront-api.umd.js` makes the 404 go away.

Now the error is: `Api.ts:750 POST http://localhost:8080/attask/api/v5.0/login net::ERR_CONNECTION_REFUSED`

**Comment by MrRoyce** [comment]
I am also not able to run the examples.  If I change the script tag to `workfront-api.umd.js` and run the login example, I get a `POST /attask/api/v5.0/login Error (404) Not found`

Any help with the examples is appreciated.

**Comment by bhovhannes** [comment]
You should have a running Workfront instance at `localhost:8080` in order to get example working.
