### ISSUE TITLE
assignCategory Action

### ISSUE THREAD

**Issue by fausto-capellan** [Workfront/workfront-api#688]
Hello folks,

I am trying to use the assignCategory action in the 9.0 version and the approaches I am trying in Postman are not working. The approaches I tried were with the URLs listed below:
`https://sub-domain.my.workfront.com/attask/api/v9.0/CTGY?ID=xxxx...&action=assignCategory&categoryID=sameCategoryID(xxxx...)&objID=xxxxxx......&objCode=PRGM`
`https://sub-domain.my.workfront.com/attask/api/v9.0/CTGY/xxxx..../assignCategory?categoryID=sameCategoryID(xxxx...)&objCode=PRGM&objID=xxxxxx......`

I also tried using the ?updates={parameters here} approach, and I kept getting the error message below:
`{
    "error": {
        "message": "Invalid Parameter: categoryIDs value \"[xxxx....]\"",
        "title": null,
        "msgKey": "exception.attask",
        "attributes": [
            ""
        ],
        "code": 0
    }
}`

Since I can't find any examples on the assignCategory action, can you folks please provide information on the error above and some examples for the action?

Thank you.

**Comment by bhovhannes** [comment]
This repo is about api client. The "Which API call should I make" aspect is not covered here.  
Better is to ask at stackoverflow: https://stackoverflow.com/questions/tagged/attask
