### ISSUE TITLE
Put / Edit not changing in Workfront

### ISSUE THREAD

**Issue by softwaretech** [Workfront/workfront-api#80]
Greetings All,

Let me first say how much I REALLY appreciate the work you guys have done.  Made it very easy to setup.  So far, in my use, I've noticed that I can send updates and get a response back, but the changes are not actually happening in Workfront.  For example, I'll edit the name of a project but the name stays the same in Workfront.

It seems that the edit is sending updates:{name:my_change}.  I've tried that directly in URL but it doesn't seem to work.  When I change my code to updates={name:my_change}, that does work.  I don't know if you guys are able to make that kind of change but certainly, your help is GREATLY appreciated!!

Thanks again!

**Comment by tkruczek** [comment]
Hi All,

I run into similar issue, where the api.edit(objCode, objId, updates) comes back successfully but doesn't actually change anything. 
I noticed that the  "updates" object is sent as PUT request body while the [API](https://developers.workfront.com/api-docs/#PUT) specifies it as query string. Not sure if API should support the updates sent in request body however using lower level api.request() method and manually appending "updates" to query string worked for me.

```
var qs = require("querystring");    

instance.request('project/593a9e590012cb31bb5d4ad9425fb259?' + qs.stringify({
        name: 'some new name'
    }), {}, null, 'PUT')
```


Thanks,
Tom

**Comment by kdparkinson** [comment]
@tkruczek Thanks for the work around. Having the same issue editing a PROJ.

**Comment by citizensas** [comment]
This issue has been fix in version 4 of workfront-api.
